### ISSUE TITLE
External Tools Invalid JSON

### ISSUE THREAD

**Issue by wbruninx** [marclelijveld/External-Tools-Model-Documentation#10]
Error message when loading external tool json : Data-Marc_ModelDocumentor.pbitool.json

Error message : invalid JSON

Power BI Desktop Release:
December 2020

Product Version:
2.88.1144.0 (20.12) (x64)

OS Version:
Microsoft Windows NT 10.0.17763.0 (x64 en-US)

CLR Version:
4.7 or later [Release Number = 461814]

Peak Virtual Memory:
38.9 GB

Private Memory:
684 MB

Peak Working Set:
986 MB

IE Version:
11.1577.17763.0

**Comment by marclelijveld** [comment]
Hi @wbruninx 

Curious to hear more about this issue. Did you make any changes to the json file? Can you also tell me more about how you tried to add the documenter to the external tools ribbon? Manual install or using Business Ops? 

Thanks!

**Comment by wbruninx** [comment]
Hi Marc,

Heb alles gedownload van GitHub
Manueel, de JSON file gekopieerd naar C:\Program Files (x86)\Common Files\microsoft shared\Power BI Desktop\External Tools
Template files & PowerShell script in C:\temp
Alles exact in dezelfde file locaties zoals in de blog beschreven.
En dan PowerBI Desktop opgestart en krijg volgende error (zie screenshot)
[cid:image001.png@01D6EDED.BF5A8160]

Mvg

/w


Sent: Monday, January 18, 2021 10:45 PM



Hi @wbruninx

Curious to hear more about this issue. Did you make any changes to the json file? Can you also tell me more about how you tried to add the documenter to the external tools ribbon? Manual install or using Business Ops?

Thanks!

**Comment by marclelijveld** [comment]
Hi, 

Can you please drop the pbitool.json file below, so I can check if there are any differences with the version that I've running at the moment? I've just tried the version as I currently have in the github repo, and that works for me. So I assume something has changed or broken while copying?

**Comment by wbruninx** [comment]
[Data-Marc_ModelDocumentor.pbitool.zip](https://github.com/marclelijveld/External-Tools-Model-Documentation/files/5849487/Data-Marc_ModelDocumentor.pbitool.zip)

**Comment by wbruninx** [comment]
[Data-Marc_ModelDocumentor.pbitool.zip](https://github.com/marclelijveld/External-Tools-Model-Documentation/files/5849499/Data-Marc_ModelDocumentor.pbitool.zip)

**Comment by wbruninx** [comment]
Didn't want to close.... Here you go with the attachment as requested.

**Comment by marclelijveld** [comment]
Hi, 

Something is definitely wrong with that file! Where did you get it? I see a lot of GitHub code around it, so it looks like you saved the webpage as pbitool.json file or something in that order. The file should look like the structure below: 
_(please know below sample is corrupt as well, as I removed the BASE64 image)_

{
	"version": "1.1.0",
	"name": "Document Model",
	"description": "This tool documents your Power BI data model in a separate Power BI report",
	"path": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
	"arguments": "C:\\temp\\Data-Marc_WriteConnectionDetailsToFile.ps1 \"%server%\" \"%database%\"",
	"iconData": {image here}"
} 

May I suggest to install the tool using[ Business Ops Installer, from PowerBI.tips](https://powerbi.tips/product/business-ops-beta/). This tool will help you to install the Model Documenter, as well as a bunch of other External Tools and drop the files in the correct location. 

Hope this helps! 
Marc
