### ISSUE TITLE
Tables : OLE DB An error was encountered in the transport layer. The peer prematurely closed connection.

### ISSUE THREAD

**Issue by garybowers1411** [marclelijveld/External-Tools-Model-Documentation#13]
I have set up your application as directed and updated the version of the OELDB connector

The app gave me a sign in which in which i tried
Database : I used data base connection and password -> failed with above error
Windows: I used my windows login -> failed with error above

![error on load in file](https://user-images.githubusercontent.com/63619405/106827232-57211400-66ed-11eb-8497-39e0c46e63b4.png)

**Comment by marclelijveld** [comment]
Hi Gary, 
I think you tried to connect to an (Azure) Analysis Services model or a published Power BI Model, right? It looks like it at least. 
If this is the case, the error makes sense. The tool doesn't support these scenarios yet. 

Thanks, 
Marc
