### ISSUE TITLE
Table description

### ISSUE THREAD

**Issue by InnaMizulina** [marclelijveld/External-Tools-Model-Documentation#15]
Please, advise where in Power BI should I put description to the table to see it in documentation? I would like to fill in [Description] column in TablesMetadata
![image](https://user-images.githubusercontent.com/80831243/111471700-38755a80-873a-11eb-8ed5-d327379cc612.png)

**Comment by marclelijveld** [comment]
Hi Inna, 
You're correct. By filling the description field in the Model View in Power BI Desktop,
![image](https://user-images.githubusercontent.com/38921736/111605393-8c358180-87d6-11eb-8ebf-58d35e91c9cd.png)
 Then it will show-up in the meta data. 
![image](https://user-images.githubusercontent.com/38921736/111605351-82138300-87d6-11eb-836b-21eab128cf83.png)

Cheers, Marc
