### ISSUE TITLE
DataSource.Error: OLE DB: Errors in the OLE DB provider

### ISSUE THREAD

**Issue by VJk17** [marclelijveld/External-Tools-Model-Documentation#17]
I'm getting below error
DataSource.Error: OLE DB: Errors in the OLE DB provider. The data source or location is not valid. Provide a valid server to which to connect

Do I need to pass the "%server%\" & "%database%\" value in .ps1 script ? can't find server and DB details. Could you please share what values we need to pass in ?

**Comment by marclelijveld** [comment]
Hi @VJk17 

The server and database should be passed automatically to the tool. This error points most likely to a live connected model. Is your report connected to an Analysis Services dataset or a dataset published in the Power BI Service? 

This is a known limitation. Please be aware that the dataset must be loaded into memory (pbix) of the PC before it can load the model documentation. 

--Marc

**Comment by marclelijveld** [comment]
Model Documenter v2.0.0 has just been released. Please check [this page](https://data-marc.com/model-documenter/) to get the latest version. All pending issues should be fixed by now. 
Also see pull request #21
