### ISSUE TITLE
Columns to Columns Metadata relatipnship

### ISSUE THREAD

**Issue by chrishopper411** [marclelijveld/External-Tools-Model-Documentation#20]
![Snag_828900e](https://user-images.githubusercontent.com/35273871/134756700-64906952-cdf9-4a59-9889-c3308dc6312e.png)

The relationship between the Columns and Columns Metadata tables seems to be off.  The [Column_ID] in the [Columns] table is a text field where the [ColumnID] in the [Columns Metadata] table is a numeric field.

Is there a better way to relate these tables?

**Comment by marclelijveld** [comment]
Let me check this on my end. Thanks for bringing this up!

**Comment by marclelijveld** [comment]
Model Documenter v2.0.0 has just been released. Please check [this page](https://data-marc.com/model-documenter/) to get the latest version. All pending issues should be fixed by now. 
Also see pull request #21
