### ISSUE TITLE
Suggestion to keep measure nicely formatted 

### ISSUE THREAD

**Issue by fuglphoenix** [marclelijveld/External-Tools-Model-Documentation#24]
Power BI removes tailing/leading spaces automatically when displaying in a table visual.
this is annoying if you have formatted your DAX code to be easy to read.
to avoid this, you can replace spaces with another UTF-8 symbol space separator like this: --> <-- (the gap between the arrows looks like a space but is another unicode charater 
[discribede here:](https://www.compart.com/en/unicode/U+2002)

`= Table.ReplaceValue(#"Changed Type"," "," ",Replacer.ReplaceText,{"Measure Expression"})`

**Comment by marclelijveld** [comment]
Hi @fuglphoenix 
Thanks for bringing this up! I will investigate this for the next version! 
--In the mean time, feel free to enhance the model documenter template report, and open a pull request if you already fixed it! 

Thanks~!
