### ISSUE TITLE
Error when trying to do a Refresh

### ISSUE THREAD

**Issue by gapendo** [marclelijveld/External-Tools-Model-Documentation#28]
Hi there, I am stuck with an error when trying to do a refresh. It says that there are pending changes in your queries that haven't been applied and when I click apply changes, it's complaining Query 'Tables' (step 'Renamed Columns1') references other queries or steps, so it may not directly access a data source. Please rebuild this data combination. Kindly see below screenshot.

![Error](https://user-images.githubusercontent.com/97990038/150022102-c8184907-b796-4476-9fe9-7aec454d372a.PNG)

**Comment by marclelijveld** [comment]
Hi @gapendo

I see you're running Model Documenter v1.x.x 
May I suggest you to upgrade to Model Documenter v2.0.1 where these kind of issues are resolved. You can read more and download v2 in [this blog](https://data-marc.com/2022/01/04/power-bi-model-documenter-v2/)

In case you first want to fix v1, then please have a look at the [FAQ](https://github.com/marclelijveld/External-Tools-Model-Documentation/wiki/2.-FAQ) and in particular [this item](https://github.com/marclelijveld/External-Tools-Model-Documentation/wiki/2.-FAQ#after-opening-the-power-bi-template-file-it-fails-loading-with-an-error-stating-that-you-need-to-rebuild-the-data-combination) which explains your case and how to solve it :) 

Thanks! 
--Marc

**Comment by gapendo** [comment]
Thank you so much @marclelijveld. I have downloaded and used the latest version it is now working perfectly. :)
