### ISSUE TITLE
Can't install after 'Windows protected your PC'

### ISSUE THREAD

**Issue by AleElf** [marclelijveld/External-Tools-Model-Documentation#34]
When lauching the downloaded file, I get the above message, as you also describes in the FAQ-page. But after clicking 'More info', I still can't proceed. The [Don't Run] button is still my only option.
Can a certificate, or something else, be added to prevent this block of installation?

**Comment by marclelijveld** [comment]
HI @AleElf, 
To me this looks like a policy on your device which prevents from installing. I would love to assign a certificate, but there are cost involved with this, which I cannot cover. 

Maybe you can reach out to your local admin and ask if they can make an exception? All code is public, so they can have a look if they want, to see themselves that there are no shady things :) 

--Marc
