### ISSUE TITLE
Unable to install version 2.0.1

### ISSUE THREAD

**Issue by TimoRiikonen** [marclelijveld/External-Tools-Model-Documentation#37]
Microsoft Defender prevents the installation:
I press More and Install Anyway.
![image](https://user-images.githubusercontent.com/10447579/162159105-9aba96c9-87f8-46f8-a07b-153c15072610.png)
Then it asks for admin user name and password.
My account has admin permissions, but perhaps there is some bug in Defender as it rejects my account id and pw.
Could you post a full installation package instead or in addition?

**Comment by marclelijveld** [comment]
Hi @TimoRiikonen, 

Sorry to hear you couldn't install... for me this has worked fine in the past. I also test every new release on a clean VM, to make sure the installation runs fine. So I'm not sure what is causing your issue and to me this looks like something local. Can you please elaborate on what you mean by a full installation package? 

--Marc

**Comment by TimoRiikonen** [comment]
Our company had changed admin permissions so that they need to be requested every time with automatic approval.
So the installation process worked correctly, I was just ignorant about the new local admin procedure.

**Comment by marclelijveld** [comment]
Hi @TimoRiikonen 

Thanks for circling back! I would be ignorant to changes to admin policies as well :) But happy to hear that installation succeeded now! 
With that, I assume this ticket can be closed? 

--Marc

**Comment by TimoRiikonen** [comment]
Hello,

Problem found: I don't have admin permissions any more. Please scrap my
problem report.

BR, Timo
