### ISSUE TITLE
Error exporting model with field parameter

### ISSUE THREAD

**Issue by charles-dh** [marclelijveld/External-Tools-Model-Documentation#39]
Hi, 

I'm using the new Field Parameter feature in the latest May 2022 release of Power BI. When I try to use Model Documenter I get the following error : 
   Error 0x0003: Error exporting vpax file. 

It works correctly with a model without any field parameter, and when I add one field parameter, I get the error. 

In DAX Studio, if I Export Metrics I get the following error message : 
![image](https://user-images.githubusercontent.com/105908894/169475034-ca45362a-9a38-4f7c-8fbb-870d65094462.png)

Thanks for your help, 

Charles

**Comment by marclelijveld** [comment]
Hi @charles-dh 
Thanks for flagging this! I'll pass this forward to the developers of the NuGet package that generates the vpax file, and see what I can do to contribute. 

In this thread I'll keep you updated on fixes for this issue. 

--Marc

**Comment by sherlockspreadsheets** [comment]
Any update on this? I'm having the same issue (see above mention: Issue https://github.com/marclelijveld/External-Tools-Model-Documentation/issues/43)

**Comment by marclelijveld** [comment]
Hi @sherlockspreadsheets and @charles-dh 

An update to this item: I finally found time to further investigate this issue. I found what is causing it and have an idea how to solve it. This might take some time, so for now I've documented a workaround and created a dedicated page to it. You can find this work-around [here](https://github.com/marclelijveld/External-Tools-Model-Documentation/wiki/3.-Work-arounds-for-known-issues)

Thanks for your patience!

**Comment by geo909** [comment]
Hi @marclelijveld,

Thank you for your effort on this bug and the project in general!

I'm having a bit of trouble with [your workaround](https://github.com/marclelijveld/External-Tools-Model-Documentation/wiki/3.-Work-arounds-for-known-issues). I'm following very closely all the steps, up to and including step 6. So far so good.

However, in Step 7, I do not see any kind of template report in `C:\Program Files (x86)\Data-Marc\ModelDocumenter`. The only files there are a .exe, a .ico, a .config and a bunch of dlls. 

Did you mean I should run the model documenter from my model in power bi, between steps 6 and 7? I tried that too, but I get the same error message as I got before trying the workaround. Am I missing something?

I am using DAX Studio 3.0.0 and PowerBI 2.109.782.0 64-bit.

Thanks again.

**Comment by marclelijveld** [comment]
Hi @geo909 

Stay tuned! I'm finalizing a newer version which solves this bug. Expect to release it next week. Currently testing in a small group :) 

I'll look at the c drive reference later today, cause I might have put the wrong location there. 

--Marc

**Comment by marclelijveld** [comment]
@geo909  The location of the template file should be: 
C:\Program Files (x86)\Common Files\Data-Marc\ModelDocumenter 
So you're missing the reference to common files :)

**Comment by marclelijveld** [comment]
Fixed with release of version v2.1.0 and merge #48
