### ISSUE TITLE
Colmn Expression Copy/Paste feature

### ISSUE THREAD

**Issue by sherlockspreadsheets** [marclelijveld/External-Tools-Model-Documentation#40]
I am fan of the V1 Model Documentation Tool. It is built into our deployment standards as part of our Enterprise BI process. I downloaded V2 and got it running nice and quick. It looks super promissing. The biggest thing that is missing is the ability to View/Copy the "Column Expression" string value. Similar to how can be done on the Table Expression, I need this functionality for Column Expression. 

After generating the documentation, I added a "Colmn Expr." hidden page to be used as a Drill Through from the Columns page (Column Name). But I do not know where the PBIT file is that this tool uses. Since the new tool uses a more complicated way of executing, I don't know who to modify the PBIT file to add this customization. 

1) How can I customize the PBIT?
2) OR, Can you add the "Colmn Expression Copy/Paste feature"?

**Github Documentation** 

https://github.com/marclelijveld/External-Tools-Model-Documentation/wiki/1.-Introduction-to-the-Power-BI-Model-Documenter#columns

**Customization Example**

![image](https://user-images.githubusercontent.com/39740261/173463537-dcfd1cf1-1743-46a6-b555-ed6498585a58.png)

![image](https://user-images.githubusercontent.com/39740261/173463525-1e57db52-d98a-4228-a3fe-cf454cc867f1.png)

**Comment by sherlockspreadsheets** [comment]
Umm, sorry. I think I answered my own question. 

According to the [Github FAQ](https://github.com/marclelijveld/External-Tools-Model-Documentation/wiki/2.-FAQ#what-changes-does-the-installation-make-to-my-machine), the "What Changes Does the Installation Make to My Machine" states:

> The template to show the model documentation in a Power BI Report is also saved on your local machine. This file is saved at `C:\Program Files (x86)\Common Files\Data-Marc\ModelDocumenter`

At this path, I found the `ModelDocumentationTemplate_v2.0.1.pbit` file. I updated this file with my changes (after making a backup), and the External Tools does include this customization when I run it. 

That should solve what I am needing.

**Comment by marclelijveld** [comment]
Hey @sherlockspreadsheets 
Thanks for reaching out. Great to hear you even made it part of your Enterprise BI Process. That's awesome to hear! You indeed found the right location. For now I'll close this issue. If there is anything in the future, please let me know! 

--Marc
