### ISSUE TITLE
Incremental Refresh info

### ISSUE THREAD

**Issue by JoyHackett** [marclelijveld/External-Tools-Model-Documentation#42]
Hi, Is there a way to capture Incremental Refresh information for each table with this tool? Thank you!

**Comment by marclelijveld** [comment]
Hi @JoyHackett 

Thanks for this nice suggestion. I'm not sure if it is possible to get this information via vpax extraction (which is used on the backend of the tool). I'll investigate and consider to add this in future versions. 

--Marc

**Comment by marclelijveld** [comment]
Enhancement in release of version v2.1.0 and merge #48

**Comment by JoyHackett** [comment]
Thank you!!
