### ISSUE TITLE
Error 0x0001: One or more arguments are not correct

### ISSUE THREAD

**Issue by zfrank67** [marclelijveld/External-Tools-Model-Documentation#46]
I got this error and couldn't find it in the FAQ.

Here's the entire log:
---
--- ModelDocumenter 2.0 for.Net (v4.0.30319)
---
Successfully loaded plugin CommandLineArgumentsParser, Version=3.0.22.0, Culture=neutral, PublicKeyToken=2990a79b704d8378 from assembly CommandLineArgumentsParser.dll
Successfully loaded plugin Dax.Metadata, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null from assembly Dax.Metadata.dll
Successfully loaded plugin Dax.Model.Extractor, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null from assembly Dax.Model.Extractor.dll
Successfully loaded plugin Dax.ViewVpaExport, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null from assembly Dax.ViewVpaExport.dll
Successfully loaded plugin Dax.Vpax, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null from assembly Dax.Vpax.dll
Successfully loaded plugin Microsoft.AnalysisServices.AdomdClient, Version=19.27.2.1, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.AdomdClient.dll
Successfully loaded plugin Microsoft.AnalysisServices.Core, Version=19.27.2.1, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.Core.dll
Successfully loaded plugin Microsoft.AnalysisServices, Version=19.27.2.1, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.dll
Successfully loaded plugin Microsoft.AnalysisServices.SPClient.Interfaces, Version=19.27.2.1, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.SPClient.Interfaces.dll
Successfully loaded plugin Microsoft.AnalysisServices.Tabular, Version=19.27.2.1, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.Tabular.dll
Successfully loaded plugin Microsoft.AnalysisServices.Tabular.Json, Version=19.27.2.1, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.Tabular.Json.dll
Successfully loaded plugin netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 from assembly netstandard.dll
Successfully loaded plugin Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed from assembly Newtonsoft.Json.dll
Successfully loaded plugin System.Diagnostics.Tracing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from assembly System.Diagnostics.Tracing.dll
Successfully loaded plugin System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 from assembly System.IO.Compression.dll
Successfully loaded plugin System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 from assembly System.IO.Compression.FileSystem.dll
Successfully loaded plugin System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from assembly System.Net.Http.dll
Argument s(server) is not marked as optional and was not found on the command line.

Usage:
        -s, --server... This parameter specifies the server name.

        -d, --database... This parameter specifies the database name.

        -f, --filename[optional]... This parameter specifies the export filename.

        -p, --pbitemplate... This parameter specifies the location of the power bi template file.

Error 0x0001: One or more arguments are not correct.

**Comment by marclelijveld** [comment]
Hi @zfrank67
Sorry to hear you're running into an error. Can you provide me a bit more details on what you're trying to do when you run into this error? 
- Did you run the tool from the external tools ribbon in Power BI Desktop? 
- Do you have the data model imported or on DirectQuery in the model, or you use a live connection to an existing dataset?
- Which version of Power BI Desktop are you running?

Thanks! 
--Marc

**Comment by zfrank67** [comment]
Oh my gosh. Marc please ignore me and forget this ever happened. I can't read basic instructions and was running the tool directly from it's .exe vs through PowerBI.
________________________________

**Comment by marclelijveld** [comment]
Glad you figured it out @zfrank67! I'll close this one.
