### ISSUE TITLE
error exporting

### ISSUE THREAD

**Issue by Larstc** [marclelijveld/External-Tools-Model-Documentation#47]
I get this error: Error 0x0003: Error exporting vpax file.
Apparently due to I have an aggregated column. 
error message (translated from Danish): The [Lead Dimensions] column is part of a composite key, but not all columns in the composite key are in the expression or dependent expression.

**Comment by Larstc** [comment]
sorry, I see it is relating to this issue: Error exporting model with field parameter #39. I look forward to the solution :-)

**Comment by marclelijveld** [comment]
Follow issue #39 for follow up on this specific issue. 
Latest update; I'm currently beta testing the new release. Expect it to be ready anytime soon!
