### ISSUE TITLE
DAX Error on Calculated Column

### ISSUE THREAD

**Issue by alexpaterson48** [marclelijveld/External-Tools-Model-Documentation#5]
ON the relationships table of the PBIT/PBIX template

ToColumn = LOOKUPVALUE ( 'Columns Metadata'[**Table**], 'Columns Metadata'[ColumnID], 'Relationships'[ToColumnID] )

Should this not return Column Name and not the Table Name

Should be 
FromColumn = LOOKUPVALUE ( 'Columns Metadata'[**Column**], 'Columns Metadata'[ColumnID], 'Relationships'[FromColumnID] )

Same applied to the FromColumn

**Comment by marclelijveld** [comment]
Thanks for flagging this! I just updated the pbit file which should fix these issues, represented in v1.1.1

Keep on contributing :) Much appreciated!
Marc
