### ISSUE TITLE
RMauzy@mac.com

### ISSUE THREAD

**Issue by RuschMauzy** [marclelijveld/External-Tools-Model-Documentation#54]
---
--- ModelDocumenter 2.0 for.Net (v4.0.30319)
---
Successfully loaded plugin CommandLineArgumentsParser, Version=3.0.22.0, Culture=neutral, PublicKeyToken=2990a79b704d8378 from assembly CommandLineArgumentsParser.dll
Successfully loaded plugin Dax.Metadata, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null from assembly Dax.Metadata.dll
Successfully loaded plugin Dax.Model.Extractor, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null from assembly Dax.Model.Extractor.dll
Successfully loaded plugin Dax.ViewVpaExport, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null from assembly Dax.ViewVpaExport.dll
Successfully loaded plugin Dax.Vpax, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null from assembly Dax.Vpax.dll
Successfully loaded plugin Microsoft.AnalysisServices.AdomdClient, Version=19.27.2.1, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.AdomdClient.dll
Successfully loaded plugin Microsoft.AnalysisServices.Core, Version=19.27.2.1, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.Core.dll
Successfully loaded plugin Microsoft.AnalysisServices, Version=19.27.2.1, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.dll
Successfully loaded plugin Microsoft.AnalysisServices.SPClient.Interfaces, Version=19.27.2.1, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.SPClient.Interfaces.dll
Successfully loaded plugin Microsoft.AnalysisServices.Tabular, Version=19.27.2.1, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.Tabular.dll
Successfully loaded plugin Microsoft.AnalysisServices.Tabular.Json, Version=19.27.2.1, Culture=neutral, PublicKeyToken=89845dcd8080cc91 from assembly Microsoft.AnalysisServices.Tabular.Json.dll
Successfully loaded plugin netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 from assembly netstandard.dll
Successfully loaded plugin Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed from assembly Newtonsoft.Json.dll
Successfully loaded plugin System.Diagnostics.Tracing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from assembly System.Diagnostics.Tracing.dll
Successfully loaded plugin System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 from assembly System.IO.Compression.dll
Successfully loaded plugin System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 from assembly System.IO.Compression.FileSystem.dll
Successfully loaded plugin System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from assembly System.Net.Http.dll
Parsing results:
        Command line:
--server localhost:51725 --database 8eab1147-814f-4e31-b083-f54cca224103 --filename c:\Power BI Model Documenter\ModelDocumenter.vpax --pbitemplate C:\Program Files\PowerBI tips Business Ops\resources\static\external-tools\020__Data_Marc\model-documenterV2\ModelDocumentationTemplate_v2.0.1.pbit

        Parsed Arguments:
Argument: s(server), type: String, value: localhost:51725 (converted from: localhost:51725)
Argument: d(database), type: String, value: 8eab1147-814f-4e31-b083-f54cca224103 (converted from: 8eab1147-814f-4e31-b083-f54cca224103)
Argument: f(filename), type: String, value: c:\Power BI Model Documenter\ModelDocumenter.vpax (converted from: c:\Power BI Model Documenter\ModelDocumenter.vpax)
Argument: p(pbitemplate), type: String, value: C:\Program Files\PowerBI tips Business Ops\resources\static\external-tools\020__Data_Marc\model-documenterV2\ModelDocumentationTemplate_v2.0.1.pbit (converted from: C:\Program Files\PowerBI tips Business Ops\resources\static\external-tools\020__Data_Marc\model-documenterV2\ModelDocumentationTemplate_v2.0.1.pbit)

        Arguments not specified:

        Additional arguments:

Query (12, 91) Column [Parameter Slicer] is part of composite key, but not all columns of the composite key are included in the expression or its dependent expression.
Error 0x0003: Error exporting vpax file.

**Comment by marclelijveld** [comment]
HI @RuschMauzy 
In the logging I see that you're using v.2.0.1 I recommend updating to the latest version first. 
After updating, can you please try again :).

**Comment by RuschMauzy** [comment]
Hi Marc, thank you for responding to me. I am new to Power BI External Tools; how do I update to the latest version?  Rusch

**Comment by marclelijveld** [comment]
@RuschMauzy easiest is to uninstall the old version via program files, and download the new one [here](https://github.com/marclelijveld/External-Tools-Model-Documentation/releases/download/v2.1.0/ModelDocumenter.Installer_v2.1.0.msi)

**Comment by marclelijveld** [comment]
Taking the fair assumption this is fixed now.
