### ISSUE TITLE
If Database name contains spaces, the name is truncated

### ISSUE THREAD

**Issue by Sodajunkie** [marclelijveld/External-Tools-Model-Documentation#6]
First of all, Kudos!  You've done a great job with the tool!

I ran across a couple of things I needed to tweak to get it to work for me.  I'll post them separately.

I have a database name of "Finance V2" that is showing in the .json file as just "Finance".  I'm hoping this is an easy fix.

**Comment by marclelijveld** [comment]
Apologies for the late response. 
The json file should be filled by the Powershell script. So this also should be a GUID. Can you please elaborate on your issue, as you talk about a name. 

Thanks! 
Marc
