### ISSUE TITLE
PBIX file connected to live PBI dataset - "The remote server returned an error: (401) Unauthorized. Error 0x0003: Error exporting vpax file."

### ISSUE THREAD

**Issue by sherlockspreadsheets** [marclelijveld/External-Tools-Model-Documentation#60]
I am getting an error message when running the PBI Documenter tool for one of our reports. This particular error message happens when I run the model documenter on in a PBIX file connected to live PBI dataset. 

According to the Wiki page, it sounds like Live Dataset Connection is supported. I am using PBI Dataset in the report, not Analysis Services connector. 

> If you run the Model Documenter from Power BI Desktop directly, you will most likely see a GUID presented. If you run the Model Documenter from Desktop connected to an existing model in the Power BI Service using the Analysis Services connector (live connection), the name of the data model will appear.

What is causing this error? How can I correct this so that PBI Documenter tool can be executed successfully?

Please advise.

Thanks,
Brian (sherlockspreadsheets)

----

ERROR:
```
The remote server returned an error: (401) Unauthorized.
Error 0x0003: Error exporting vpax file.
```

![image](https://github.com/marclelijveld/External-Tools-Model-Documentation/assets/39740261/8b06f743-8e20-4251-ab3f-9e8ba4424160)

**Comment by sherlockspreadsheets** [comment]
I did a little test, and tried using "Analysis Services (AS)"  connector instead of "PBI Dataset". 

We have PBI Premium workspaces, so I used entered the XMLA endpoint into the server connection for AS. I was able to connect to the exact same model using AS. I ran the PBI Documenter and this time it completed successfully. As far as I can tell, both "analysis services" data connectors work the same. 

![image](https://github.com/marclelijveld/External-Tools-Model-Documentation/assets/39740261/7c323af5-8bd3-4c3b-9255-d16495e82984)

**Comment by marclelijveld** [comment]
Hi @sherlockspreadsheets, 
Thanks for reaching out! Using the Analysis Service connector (AS & AAS) should both work indeed and is how the tool is supposed to work. Live connections unfortunately don't work due to a limitation on Microsoft side. This is because they don't allow us to read / create a vpax file over a live connection. 

Hope this confirms your line of thought :) 
--Marc
