### ISSUE TITLE
PowerShell script not found in Git

### ISSUE THREAD

**Issue by jgiraomlf** [marclelijveld/External-Tools-Model-Documentation#61]
Please could you check if the file is missing?

I only see these files:

![2024-05-23_10h43_41](https://github.com/marclelijveld/External-Tools-Model-Documentation/assets/132611378/1993f369-578b-49ae-84e9-e93756171a41)

Tks

**Comment by marclelijveld** [comment]
Which PowerShell script are you looking for? What is it you try to do that brings you to the PowerShell script? 
I need a bit more context... cause Model Documenter v2.1.0 doesn't run on PowerShell anymore. So if you're still using the older versions, I would recommend upgrading to the latest version.

**Comment by jgiraomlf** [comment]
Oh, sorry, I didn't know PowerShell wasn't used anymore. I'm following [this steps](https://data-marc.com/2020/07/28/external-tools-document-your-power-bi-model/#:~:text=How%20it%20works%201%20Open%20a%20Power%20BI,and%20the%20.pbit%20template%20file%20will%20open%20directly.) (Step 3), and there is a power shell file there. 

In this new version, do I simply ignore this file?

Thanks for your reply.

![image](https://github.com/marclelijveld/External-Tools-Model-Documentation/assets/132611378/495e5b45-7362-4c4d-be23-d6c924901930)

**Comment by marclelijveld** [comment]
Please use the latest version (v2.1.0), download the MSI installer and install from there. The latest version does not use any PowerShell anymore. You can find the release notes and download [here](https://github.com/marclelijveld/External-Tools-Model-Documentation/releases/tag/v2.1.0)

--Marc
