### ISSUE TITLE
Provide a way to use a Perspective when connecting to SSAS

### ISSUE THREAD

**Issue by Sodajunkie** [marclelijveld/External-Tools-Model-Documentation#7]
I have two perspectives in my SSAS database.  When I try to connect, I get errors.  I was able to modify the connection string to include the name of my perspective but it wasn't intuitive.  The connection property is "**Cube=**_perspectivename_".  If there's an easy way to add it, that would be great.  

https://docs.microsoft.com/en-us/analysis-services/instances/connection-string-properties-analysis-services?view=asallproducts-allversions#cube

**Comment by marclelijveld** [comment]
This relates to Analysis Services, which is not the focus of this External Tool. For now, I've listed it down as possible future enhancement. 

If you feel like it, feel free to contribute to this repo. 

Thanks,
Marc
